spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "/**"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: function-service
          uri: lb://FUNCTION-SERVICE
          predicates:
            - Path=/master/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: master-service
#                fallbackuri: forward:/masterdown
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: booking-service
#                fallbackuri: forward:/bookingdown
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: auth-service
#                fallbackuri: forward:/authdown        
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**



server:
  port: 8989

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9999999999999999999999999999999999999999999999999999999999999999
